name: vendor_management_system
description: "semester project 6th semester"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # Utility Packages

  # State Management


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to

  flutter_lints: ^3.0.0


flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/on_boarding_images/
     - assets/fonts/
     - assets/logos/
     - assets/icons/


  # example:
 # fonts:
  #- family: Schyler
   # fonts:
    #  - asset: fonts/Schyler-Regular.ttf
     # - asset: fonts/Schyler-Italic.ttf
     #   style: italic
  #- family: Trajan Pro
   # fonts:
    #  - asset: fonts/TrajanPro.ttf
     # - asset: fonts/TrajanPro_Bold.ttf
      #  weight: 700
fonts:
  - family: Summer Farmhouse
  - asset: assets/fonts/Summer Farmhouse.otf
    fonts:
     - family: poppin
       -asset: assets/fonts/Poppin-Regular.otf

